repos:
-   repo: local
    hooks:

    # -   id: activate
    #     name: activate
    #     entry: pyt1/env310/Scripts/activate.bat
    #     language: script
    #     pass_filenames: false
    #     # alternatively you could `types: [python]` so it only runs when python files change
    #     # though tests might be invalidated if you were to say change a data file
    #     always_run: true

    -   id: pytest
        name: pytest
        entry: pyt1/env310/Scripts/python.exe -m pytest pyt1/tests/
        language: script
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true

    -   id: pyright
        name: pyright
        entry: pyt1/env310/Scripts/python.exe -m pyright pyt1/epure --project pyt1 --pythonversion 3.10
        # args: [--project, pyt1] --pythonversion 3.10
        language: script
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true