repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pyt/env39/Scripts/python.exe -m pytest
        language: script
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true
    # -   id: mypy
    #     name: mypy
    #     entry: pyt/env39/Scripts/python.exe -m mypy pyt/epure
    #     language: script
    #     pass_filenames: false
    #     # alternatively you could `types: [python]` so it only runs when python files change
    #     # though tests might be invalidated if you were to say change a data file
    #     always_run: true