
' enum box{
'     null(abstract)
'     this(parent)
'     Storage.get(storageName)
' }

class Epure{
    parent
    __new__()    
    save(make, storage)
    take(storage)
    delete(storage)

    storage()

    pack(): row
    unpack(row)
}

class Node{
    add()
    get()
    mask
}

' Storage <|-- EpureStorage
' EpureBox *--> Epure
' Model --> container
Epure --> Node
' Node <|-up- Primitive


Node *--> Node
Node <|-left- Storage
Storage <|-left- Table
' Storage <|-- NoSql

Epure --|> Node
Epure <|-left- DBEpure
Field -up-|> Epure
DBEpure -left-> DB
Field <|-- Table
DB *--> Table
Table --> Header
Table *--> Row

Category *-right-> Ref
Node <|-right- Category
Node --> Mask


' Model --> View
' Category <|-- View
' View o--> Model

Category <|-- Role
' Access -up-> Node
    Access -right-> Role
    Access -left-> Mask
    Access -up-> Node
    ' Access -down-> Predicate

' Migration --> BD
' Migration --> Epure