class Resource{    
    create(Savable resource, res_id=None)
    read(Object)
    update(Savable resource, res_id=None)
    delete(Savable resource, res_id=None ? Object)

    create_all(List[Savable])
    update_all(List[Savable])
    delete_all(?)
    
    "execute"(str script='')
    res_id
    name
}


class Db{
    init(str connect_str)
}

class GresDb{}
class LiteDb{}

class Savable{    
    resource
    save(int level=0)
    serialize()
    deserialize()    
}

class Table{
    name = res_id
}

class GresTable{}
class JsonbTable{}
class LiteTable{}

class TableHeader{}
class TableColumn{}
class NotNull{}

class FileResource{
    init(str path)
}

class IniFile{}
class IniSection{}
class NoneIniSection{}
class JsonFile{}

class Node{
    table = resource
    db = resource.resource
    "__exclude__"
    save(int level)
    is_excluded(str atr_name)
}




Resource <|-left- Db
    Db <|-up- GresDb
    Db <|-left- LiteDb
    Db o-down-> Table
Resource <|-- Savable
Resource o--> Savable
    Savable <|-right- FileResource
        FileResource <|-up- IniFile
            IniFile o--> NoneIniSection
                NoneIniSection <|-- IniSection
        FileResource <|-- JsonFile
    Savable <|-left- Table
        Table <|-left- GresTable
            GresTable <|-- JsonbTable
        Table <|-- LiteTable
        Table --> TableHeader
    Savable <|-right- Node
    Savable <|-- TableHeader
        TableHeader o-right-> TableColumn
    Savable <|-- TableColumn