class Storage{    
    put(Savable storage)
    put_all(List[Savable])
    search(Object)
    delete(Objest)
    execute(str script='')
    name
}

class Db{
    init(str connect_str)
}

class GresDb{}
class LiteDb{}

class Savable{    
    storage
    save(int level=0)
    serialize()
    deserialize()    
}

class Table{}

class GresTable{}
class LiteTable{}

class TableHeader{}
class TableColumn{}

class FileStorage{
    init(str path)
}

class IniFile{}
class IniSection{}
class NoneIniSection{}
class ActualIniSection{}
class JsonFile{}

class Node{
    table
    db
    exclude
    save(int level)
    is_excluded(str atr_name)
}


Storage <|-left- Db
    Db <|-up- GresDb
    Db <|-left- LiteDb
    Db o-down-> Table
Storage <|-- Savable
Storage o--> Savable
    Savable <|-right- FileStorage
        FileStorage <|-up- IniFile
            IniFile o--> IniSection
                IniSection <|-- NoneIniSection
                IniSection <|-- ActualIniSection
        FileStorage <|-- JsonFile
    Savable <|-left- Table
        Table <|-left- GresTable
        Table <|-- LiteTable
        Table --> TableHeader
    Savable <|-right- Node
    Savable <|-- TableHeader
        TableHeader o-right-> TableColumn
    Savable <|-- TableColumn