#!/bin/sh -e

# -   "repo": local
#     "hooks":
#     # -   id: pytest
#     #     name: pytest
#     #     # entry: venv/bin/pytest
#     #     entry: ..pyt/env39/Lib/site-packages/pytest
#     #     language: script
#     #     pass_filenames: false
#     #     # alternatively you could `types: [python]` so it only runs when python files change
#     #     # though tests might be invalidated if you were to say change a data file
#     #     always_run: true
#         -   "id": pytest
#         "name": pytest
#         # entry: venv/bin/pytest
#         "entry": ..pyt/env39/Lib/site-packages/pytest
#         "language": script
#         "pass_filenames": false
#         # alternatively you could `types: [python]` so it only runs when python files change
#         # though tests might be invalidated if you were to say change a data file
#         "always_run": true

# "id": "check-ast",
#             "name": "check python ast",
#             "description": "simply checks whether the files parse as valid python.",
#             "entry": "check-ast",
#             "language": "python",
#             "types": [
#                 "python"
#             ]