[tool.poetry]
name = "epure"
version = "0.1.0"
description = "purest architecture"
authors = ["nagvalhm <nagvalhm@yandex.ru>"]
license = "MIT"
packages = [
    { include = "pypi_stub" },
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
